### PR TITLE
Reorder installs for Poetry

### PR DESCRIPTION
**Pull request by teutoburg**

### CODE REVIEW

**Comment by teutoburg** [comment]
The workflow run on this branch passed: https://github.com/AstarVienna/ScopeSim_Data/actions/runs/10653774693

So I guess we can do it this way for now...

**Comment by hugobuddel** [comment]
It passes, but I think it is using ScopeSim 0.8.4 now, as this is one of the last lines for the installation part:
```
2024-09-01T12:00:30.1854218Z   - Downgrading scopesim (0.9.0a0 /tmp/tmp.XAnah81jat/ScopeSim -> 0.8.4)
```
so we are not testing the latest development version of all our packages.

I think we should switch to `pip install .`, or maybe `pip install github-url`?

**Comment by teutoburg** [comment]
> It passes, but I think it is using ScopeSim 0.8.4 now, as this is one of the last lines for the installation part:
> ```
> 2024-09-01T12:00:30.1854218Z   - Downgrading scopesim (0.9.0a0 /tmp/tmp.XAnah81jat/ScopeSim -> 0.8.4)
> ```
> so we are not testing the latest development version of all our packages.
> 
> I think we should switch to `pip install .`, or maybe `pip install github-url`?

I see the problem. What would be the functional difference between `git clone foo` plus `pip install .` as opposed to `pip install github-url`? Or would you still clone in the latter case?

**Comment by hugobuddel** [comment]
> > so we are not testing the latest development version of all our packages.
> > I think we should switch to `pip install .`, or maybe `pip install github-url`?
> 
> I see the problem. What would be the functional difference between `git clone foo` plus `pip install .` as opposed to `pip install github-url`? Or would you still clone in the latter case?

A `pip install github-url` would not really work, because then the git clone would not be available to run the tests from. (Well, pip would have made a git clone, but no clue where.)

**Pull request merged**
